config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 resources :articles

 root'pages#home'
 get 'about', to: 'pages#about'

 get 'signup', to: 'users#new'
 resources :users, except: [:new]

 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true, length: {minimum: 3, maximum: 50}
	validates :description, presence: true, length: {minimum: 10, maximum: 300}
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles, dependent: :destroy

	before_save {self.email.downcase!}
	validates :username, presence: true, 
					uniqueness: { case_sensitive: false }, 
					length: {minimum: 3, maximum: 25}
	VALID_EMAIL_REGEX = /.+\@.+\..+/i
	validates :email, presence: true, 
					uniqueness: { case_sensitive: false }, 
					format: { with: VALID_EMAIL_REGEX }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	

	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:danger] = "Operation impossible si tu n'es pas connecté"
			redirect_to root_path
		end
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]


	def index
		@articles =Article.paginate(:page => params[:page], per_page: 5)
	end

	def new
		@article = Article.new
	end

	def edit
		
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:success] = "Article bel et bien crée"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def update
		
		if @article.update(article_params)
			flash[:success] = "Article bel et bien modifié"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def show
		
	end

	def destroy
		
		@article.destroy
		flash[:success] = "Article bel et bien supprimé"
		redirect_to articles_path
	end

	private

	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description)
	end

	def require_same_user
		if current_user != @article.user and current_user.admin? == false
			flash[:danger] = "Ce n'est pas ton article"
			redirect_to root_path
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		redirect_to articles_path if logged_in?
	end
	def about
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		user = User.find_by(email: params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			flash[:success] = "Felicitations de cette connexion !"
			session[:user_id] = user.id
			redirect_to user_path(user)
		else
			flash.now[:danger] = "Identifiant incorrect"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "Au revoir"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show , :destroy]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only: [:destroy]

	def index
		@users = User.paginate(page: params[:page], per_page: 5)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "New user #{@user.username} created"
			redirect_to user_path(@user)
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @user.update(user_params)
			flash[:succes] = "User mis à jour avec succès !"
			redirect_to articles_path
		else
			render 'edit'
		end		
	end

	def show
		@user_articles = @user.articles.paginate(:page => params[:page], per_page: 5)
	end

	def destroy
		@user.destroy
		flash[:success] = " Utilisateur et tous ses articles supprimés avec succès"
		redirect_to users_path
	end

	private

	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def require_same_user
		if current_user != @user and current_user.admin? == false
			flash[:danger] = "Ce n'est pas ton profil !"
			redirect_to root_path
		end
	end

	def require_admin
		if logged_in? and current_user.admin? == false
			flash[:danger] = "Action impossible si tu n'es pas admin"
			redirect_to users_path
		end	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for(user, options = { size: 200})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/views/articles/_articles.html.erb
<table class="table">
	<thead>
		<tr>
			<th>Titre</th>
			<th>Description</th>
			<th>Informations</th>
			<th>Actions</th>
		</tr>
	</thead>

	<% obj.each do |article| %>
	<tr>
		<td><%= link_to article.title, article_path(article) %></td>		
		<td><%= truncate(article.description, length: 60) %></td>	
		<td><small>Created by <strong> <%= article.user.username if article.user %></strong> <%= time_ago_in_words(article.created_at) %> ago, 
						updated <%= time_ago_in_words(article.updated_at) %> ago</small></td>	
		<% if logged_in? and (current_user == article.user or current_user.admin?) %>			
			<td><%= link_to "Editer", edit_article_path(article), class: "btn btn-xs btn-primary" %></td>
			<td><%= link_to "Supprimer", article_path(article), method: :delete, class: "btn btn-xs btn-danger" %></td>
		<% end %>
	</tr>	
	<% end %>	

</table>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
	
	<%= form_for(@article, :html => {class: "form-horizontal", role: "form"})do |f| %>
		<div class="form-group">
			<div class="col-sm-2 control-label">
				<%=f.label :title %>
			</div>
			<div class="col-sm-6">
				<%=f.text_field :title, class: "form-control", placeholder: "Titre de l'article"%>
			</div>
		</div>	

		<div class="form-group">
			<div class="col-sm-2 control-label">
				<%=f.label :description %>
			</div>
			<div class="col-sm-6">
				<%=f.text_area :description, rows: 10, class: "form-control", placeholder: "Description"%>
			</div>
		</div>			

		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<%=f.submit class: "btn btn-default" %>
			</div>
		</div>
	<% end %>

</div>

<div class="col-sm-offset-2">
	<%= link_to "Retour à la liste", articles_path %>
</div>

app/views/articles/edit.html.erb
<h1 class="col-sm-offset-2">Editer un article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		
		<h1> Listing de tous les articles </h1>
		<p>
		 	<%= link_to "Créer nouvel article", new_article_path %>
		</p>
		<div align="center">
			<%= will_paginate @articles %>
		</div>
		<%= render 'articles', obj: @articles %>
		<div align="center">
			<%= will_paginate @articles %>
		</div>
	</div>
</div>

app/views/articles/new.html.erb
<h1 class="col-sm-offset-2">Creation d'un article !</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="row">
	<div class="col-xs-offset-2 col-xs-10">
		<h2><%= @article.title %></h2>
		
		<div class="well col-xs-6">
			<%= @article.description %>


			<% if @article.user %>
				<div class="article-actions">
					<%= gravatar_for @article.user, size:50 %><br>
					<small>Article créé par <%= link_to @article.user.username, user_path(@article.user) %></small>
				</div>
			<% end %>
			<div class="article-actions">
				<% if logged_in? and (current_user == @article.user or current_user.admin?) %>
					<%= link_to "Editer l'article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
					<%= link_to "Supprimer cet article", article_path(@article), method: :delete, class: "btn btn-xs btn-danger" %>
				<% end %>
				<%= link_to "Retour à la liste", articles_path, class: "btn btn-xs btn-success" %>
			</div>	
		</div>
	</div>	
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer>
		<small>
			<%= link_to "All Sport Pro","https://www.allsportpro.com"%> Copyright by Fabi
		</small>
		<nav>
			<ul>
				<li><%= link_to "A propos", about_path %></li>
			</ul>
		</nav>
	</footer>

<div/>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
			<div class='alert alert-<%= "#{name}" %>'>
				<a href="#" class="close" data-dismiss="alert">&#215;</a>
				<%= content_tag :div, msg, :id => "flash-#{name}" if msg.is_a?(String) %>
			</div>
		<% end %>
	</div>
</div>


	

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "All Sport Pro Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Les sports", about_path, id: "logo1" %></li>
        <li><%= link_to "Musculation", articles_path , id: "logo2"%></li>
        <li><%= link_to "Utilisateurs", users_path , id: "logo3"%></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><li><%= link_to "Nouvel Article", new_article_path %></li></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Se déconnecter", logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profil 
            <%="(admin)" if current_user.admin? %>  <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Afficher le profil", user_path(current_user) %></li>
              <li><%= link_to "Editer mon profil", edit_user_path(current_user) %></li>          
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Se connecter", login_path %></li>
          <li><%= link_to "S'inscrire", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Bienvenue sur about</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="center container">
	<div class="jumbotron">
	  <h1>All sport pro</h1>
	  <p>Bienvenue sur All Sport Pro</p>
	  <%= link_to "S'inscrire", signup_path, class: "btn btn-primary btn-lg" %>
	</div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="col-xs-6 col-xs-offset-2">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h2 class="panel-title">
						<%= pluralize(obj.errors.count, "erreur") %> nous avons, Jean
					</h2>
					<div class="panel-body"
						<ul>
						<% obj.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
	
	<%= form_for(@user, :html => {class: "form-horizontal", role: "form"})do |f| %>
		<div class="form-group">
			<div class="col-sm-2 control-label">
				<%=f.label :username %>
			</div>
			<div class="col-sm-6">
				<%=f.text_field :username, class: "form-control", placeholder: "Votre username"%>
			</div>
		</div>	

		<div class="form-group">
			<div class="col-sm-2 control-label">
				<%=f.label :email %>
			</div>
			<div class="col-sm-6">
				<%=f.text_field :email, class: "form-control", placeholder: "Votre email"%>
			</div>
		</div>			
		
		<div class="form-group">
			<div class="col-sm-2 control-label">
				<%=f.label :password %>
			</div>
			<div class="col-sm-6">
				<%=f.password_field :password, class: "form-control", placeholder: "Votre mot de passe"%>
			</div>
		</div>			


		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<%=f.submit(@user.new_record? ? "S'inscrire" : "Mettre à jour", class: "btn btn-default") %>
			</div>
		</div>
	<% end %>

</div>

<div class="col-sm-offset-2">
	<%= link_to "Retour à la liste des articles", articles_path %>
</div>

app/views/users/edit.html.erb
<h1 align="center">Editer un user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">Liste des utilisateurs</h1>

<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div align="center">
			<%= will_paginate @users %>
		</div>
		<ul class="list-group">
			<% @users.each do |user| %>
				<div class="panel panel-default">
				  <div class="panel-heading">
				    <h3 class="panel-title">
				    	<%= gravatar_for user, size:25 %>
				    	<%= link_to user.username, user_path(user)%>
				    	<% if logged_in? and current_user.admin? %>
				    		<%= link_to "Supprimer l'utilisateur", user_path(user), method: :delete, 
				    			data: {confirm: "Etes vous sur de vouloir supprimer cet utilisateur et ses articles?"}, 
				    			class: "btn btn-xs btn-danger" 
				    		%>
				    	<% end %>
				    </h3>
				  </div>
				  <div class="panel-body">
				    <%= pluralize(user.articles.count, "article") if user.articles %>
				  </div>
				</div>
				<li class="list-group-item">Cras justo odio</li>
			<% end %>
		</ul>
		<div align="center">
			<%= will_paginate @users %>
		</div>	
	</div>
</div>

app/views/users/new.html.erb
<h1 align="center">Créer nouvel user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Bienvenue <%= @user.username %></h1>

<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= gravatar_for @user, size: 120 %>
	</div>	
</div>
<h4 align="center">Articles de <%= @user.username %></h4>

<div class="row">
	<div class="col-md-6 col-md-offset-3 center">
		<%= will_paginate @user_articles %>
		<%= render 'articles/articles', obj: @user_articles %>
		<%= will_paginate @user_articles %>
	</div>	
</div>